#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header 


sudo apt-get update
sudo apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/error_404.html

sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

printf %s "server {
    add_header X-Served-By $HOSTNAME;
}" > /etc/nginx/sites-available/default

sudo service nginx restart
