#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt install -y haproxy=2.4.\*
sudo apt update && sudo apt upgrade -y

echo "ENABLED=1" > /etc/default/haproxy

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 449-web-01 34.139.131.161:80 check
    server 449-web-02 44.200.101.61:80 check
" > /etc/haproxy/haproxy.cfg

service haproxy start
