#!/usr/bin/env bash
# displays to infinity and beyond indefinitely with sleep 2 ....i am invicible!!! when receiving and SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true;do
	echo "To infinity and beyond";
	sleep 2
done
