#!/usr/bin/env bash

i=0

while [[ $i -le 20 ]];do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luch from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
