#!/usr/bin/env bash
# gives you information about the school file

if [[ -e "school" ]];then
	echo "school file exist"
	if [[ ! -s "school" ]];then
		echo "school file is empty"
	else
		echo "school file is empty"
	if [[ -f "school" ]];then
		echo "school is a regular file"
	fi
	fi
else
	echo "school file does not exists"
fi
