#!/usr/usr/env bash
# configures an ubuntu server with the below requirements

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
sed -i "\$a 8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
